### PR TITLE
Request to Add new .NET library for MongoDB

### PR DESCRIPTION
**Pull request by rishitb-mongodb**
The MongoDB OData extension for .NET is built on top of the MongoDB C# Driver. It allows developers intending to use OData to power their REST APIs with MongoDB quickly and seamlessly.

### CODE REVIEW

**Comment by rishitb-mongodb** [comment]
@microsoft-github-policy-service agree company="MongoDB"

**Comment by rishitb-mongodb** [comment]
@mikepizzo @marabooy @xuzhg Could you please take a look at this when you get a chance?

**Review by mikepizzo — APPROVED** [review]
Thanks for the submission!  We will get this merged right away, but it may be a couple weeks before we are able to get the changes propagated to the public site.

**Review by marabooy — APPROVED** [review]

**Comment by rishitb-mongodb** [comment]
Hi @mikepizzo Just checking in to see if this change can be propagated to the public [website](https://www.odata.org/libraries/)?

**Pull request merged**
